---
- hosts: all
  become: true
  pre_tasks:
    - name: install dependencies
      apt:
        name: "git"
        state: "present"
    - name: install dependencies
      apt:
        name: "docker"
        state: "present"
    - name: install dependencies
      apt:
        name: "docker-compose"
        state: "present"
  roles:
  - asemin08.gestionglasses_role
